In [1]:
import numpy as np
import pandas as pd

In [2]:
a=[1,2,3,4,5,6,7,8,9]

In [3]:
type(a)

list

In [4]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
c=np.array(a)

In [6]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
c.ndim

1

In [8]:
c=np.array(a,ndmin=2)

In [9]:
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
c=np.array(a,ndmin=3)

In [11]:
c

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [12]:
#a[2][2][2][2]

In [13]:
c=np.arange(24)

In [14]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
c.ndim

1

In [16]:
c.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
c.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
c.ndim

1

In [20]:
x=c.reshape(2,3,2,2)

In [21]:
x

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [22]:
x.ndim

4

In [23]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [24]:
a

array([[1, 2],
       [3, 4]])

In [25]:
b

array([[5, 6],
       [7, 8]])

In [26]:
c=np.concatenate((a,b))

In [27]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
c=np.concatenate((a,b),axis=1)

In [31]:
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
c=np.hstack((a,b))

In [33]:
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [34]:
c=np.vstack((a,b))

In [35]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
c=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30],[31,32,33,34,35,36]])

In [37]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [38]:
df=pd.DataFrame(c)

In [39]:
df

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30
5  31  32  33  34  35  36

In [40]:
c[2:5,:3]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [41]:
df

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30
5  31  32  33  34  35  36

In [42]:
c[1:5,2:5]

array([[ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [43]:
df

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30
5  31  32  33  34  35  36

In [45]:
c[[0,0,2,2,4,4],[0,2,0,2,0,2]]

array([ 1,  3, 13, 15, 25, 27])

In [46]:
df

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30
5  31  32  33  34  35  36

In [48]:
x=c[[[0,0,2],[2,2,4]],[[0,2,0],[2,0,2]]]

In [49]:
x

array([[ 1,  3, 13],
       [15, 13, 27]])

In [50]:
x.shape

(2, 3)

In [51]:
a

array([[1, 2],
       [3, 4]])

In [52]:
b

array([[5, 6],
       [7, 8]])

In [53]:
c=np.add(a,b)

In [55]:
c

array([[ 6,  8],
       [10, 12]])

In [56]:
c=np.subtract(a,b)

In [57]:
c

array([[-4, -4],
       [-4, -4]])

In [58]:
c=np.multiply(a,b)

In [59]:
c

array([[ 5, 12],
       [21, 32]])

In [60]:
c=np.divide(a,b)

In [61]:
c

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [62]:
a

array([[1, 2],
       [3, 4]])

In [63]:
b

array([[5, 6],
       [7, 8]])

In [64]:
x=np.dot(a,b)

In [65]:
x

array([[19, 22],
       [43, 50]])